//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-11\\SQLEXPRESS;Initial Catalog=DA_QL_KTX;User ID=sa;Password=1" +
            "23;TrustServerCertificate=True")]
        public string DA_QL_KTXConnectionString {
            get {
                return ((string)(this["DA_QL_KTXConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RUL1LBP2\\SQLEXPRESS;Initial Catalog=DA_QL_KTX5;User ID=sa;Pass" +
            "word=123;TrustServerCertificate=True")]
        public string DA_QL_KTX5ConnectionString {
            get {
                return ((string)(this["DA_QL_KTX5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-71LH3C1\\SQLEXPRESS;Initial Catalog=DA_QL_KTX3;User ID=sa;Pass" +
            "word=123")]
        public string DA_QL_KTX3ConnectionString {
            get {
                return ((string)(this["DA_QL_KTX3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHANG-HUYNH\\TESTD8;Initial Catalog=DA_QL_KTX;User ID=sa;Password=123;" +
            "TrustServerCertificate=True")]
        public string DA_QL_KTXConnectionString1 {
            get {
                return ((string)(this["DA_QL_KTXConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RUL1LBP2\\SQLEXPRESS;Initial Catalog=DA_QL_KTX7;User ID=sa;Pass" +
            "word=123;TrustServerCertificate=True")]
        public string DA_QL_KTX7ConnectionString {
            get {
                return ((string)(this["DA_QL_KTX7ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-11\\SQLEXPRESS;Initial Catalog=DA_QL_KTX;User ID=sa;Password=1" +
            "23;Encrypt=True;TrustServerCertificate=True")]
        public string DA_QL_KTXConnectionString2 {
            get {
                return ((string)(this["DA_QL_KTXConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RUL1LBP2\\SQLEXPRESS;Initial Catalog=DA_QL_KTX;User ID=sa;Passw" +
            "ord=123;TrustServerCertificate=True")]
        public string DA_QL_KTXConnectionString3 {
            get {
                return ((string)(this["DA_QL_KTXConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-71LH3C1\\SQLEXPRESS;Initial Catalog=DA_QL_KTX;User ID=sa;Passw" +
            "ord=123")]
        public string DA_QL_KTXConnectionString4 {
            get {
                return ((string)(this["DA_QL_KTXConnectionString4"]));
            }
        }
    }
}
